package com.travelgo.otpb.domain;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of City.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class City implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** cityId. */
	private Integer cityid;

	/** cityName. */
	private String cityname;

	/** The set of hotel. */
	private Set<Hotel> hotelSet;

	/**
	 * Constructor.
	 */
	public City() {
		this.hotelSet = new HashSet<Hotel>();
	}

	/**
	 * Set the cityId.
	 * 
	 * @param cityid
	 *            cityId
	 */
	public void setCityid(Integer cityid) {
		this.cityid = cityid;
	}

	/**
	 * Get the cityId.
	 * 
	 * @return cityId
	 */
	public Integer getCityid() {
		return this.cityid;
	}

	/**
	 * Set the cityName.
	 * 
	 * @param cityname
	 *            cityName
	 */
	public void setCityname(String cityname) {
		this.cityname = cityname;
	}

	/**
	 * Get the cityName.
	 * 
	 * @return cityName
	 */
	public String getCityname() {
		return this.cityname;
	}

	/**
	 * Set the set of the hotel.
	 * 
	 * @param hotelSet
	 *            The set of hotel
	 */
	public void setHotelSet(Set<Hotel> hotelSet) {
		this.hotelSet = hotelSet;
	}

	/**
	 * Add the hotel.
	 * 
	 * @param hotel
	 *            hotel
	 */
	public void addHotel(Hotel hotel) {
		this.hotelSet.add(hotel);
	}

	/**
	 * Get the set of the hotel.
	 * 
	 * @return The set of hotel
	 */
	public Set<Hotel> getHotelSet() {
		return this.hotelSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((cityid == null) ? 0 : cityid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		City other = (City) obj;
		if (cityid == null) {
			if (other.cityid != null) {
				return false;
			}
		} else if (!cityid.equals(other.cityid)) {
			return false;
		}
		return true;
	}

}
