package com.travelgo.otpb.domain;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of Comment.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Comment implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** commentId. */
	private Integer commentid;

	/** message. */
	private String message;

	/** date. */
	private Date date;

	/** product. */
	private Product product;

	/**
	 * Constructor.
	 */
	public Comment() {
	}

	/**
	 * Set the commentId.
	 * 
	 * @param commentid
	 *            commentId
	 */
	public void setCommentid(Integer commentid) {
		this.commentid = commentid;
	}

	/**
	 * Get the commentId.
	 * 
	 * @return commentId
	 */
	public Integer getCommentid() {
		return this.commentid;
	}

	/**
	 * Set the message.
	 * 
	 * @param message
	 *            message
	 */
	public void setMessage(String message) {
		this.message = message;
	}

	/**
	 * Get the message.
	 * 
	 * @return message
	 */
	public String getMessage() {
		return this.message;
	}

	/**
	 * Set the date.
	 * 
	 * @param date
	 *            date
	 */
	public void setDate(Date date) {
		this.date = date;
	}

	/**
	 * Get the date.
	 * 
	 * @return date
	 */
	public Date getDate() {
		return this.date;
	}

	/**
	 * Set the product.
	 * 
	 * @param product
	 *            product
	 */
	public void setProduct(Product product) {
		this.product = product;
	}

	/**
	 * Get the product.
	 * 
	 * @return product
	 */
	public Product getProduct() {
		return this.product;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((commentid == null) ? 0 : commentid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Comment other = (Comment) obj;
		if (commentid == null) {
			if (other.commentid != null) {
				return false;
			}
		} else if (!commentid.equals(other.commentid)) {
			return false;
		}
		return true;
	}

}
