package com.travelgo.otpb.domain;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of hotel.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Hotel implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** hotelId. */
	private Integer hotelid;

	/** City. */
	private City city;

	/** hotelName. */
	private String hotelname;

	/** The set of product. */
	private Set<Product> productSet;

	/**
	 * Constructor.
	 */
	public Hotel() {
		this.productSet = new HashSet<Product>();
	}

	/**
	 * Set the hotelId.
	 * 
	 * @param hotelid
	 *            hotelId
	 */
	public void setHotelid(Integer hotelid) {
		this.hotelid = hotelid;
	}

	/**
	 * Get the hotelId.
	 * 
	 * @return hotelId
	 */
	public Integer getHotelid() {
		return this.hotelid;
	}

	/**
	 * Set the City.
	 * 
	 * @param city
	 *            City
	 */
	public void setCity(City city) {
		this.city = city;
	}

	/**
	 * Get the City.
	 * 
	 * @return City
	 */
	public City getCity() {
		return this.city;
	}

	/**
	 * Set the hotelName.
	 * 
	 * @param hotelname
	 *            hotelName
	 */
	public void setHotelname(String hotelname) {
		this.hotelname = hotelname;
	}

	/**
	 * Get the hotelName.
	 * 
	 * @return hotelName
	 */
	public String getHotelname() {
		return this.hotelname;
	}

	/**
	 * Set the set of the product.
	 * 
	 * @param productSet
	 *            The set of product
	 */
	public void setProductSet(Set<Product> productSet) {
		this.productSet = productSet;
	}

	/**
	 * Add the product.
	 * 
	 * @param product
	 *            product
	 */
	public void addProduct(Product product) {
		this.productSet.add(product);
	}

	/**
	 * Get the set of the product.
	 * 
	 * @return The set of product
	 */
	public Set<Product> getProductSet() {
		return this.productSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((hotelid == null) ? 0 : hotelid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Hotel other = (Hotel) obj;
		if (hotelid == null) {
			if (other.hotelid != null) {
				return false;
			}
		} else if (!hotelid.equals(other.hotelid)) {
			return false;
		}
		return true;
	}

}
