package com.travelgo.otpb.domain;

import java.io.Serializable;

/**
 * Model class of Itinerary.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Itinerary implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** itineraryId. */
	private Integer itineraryid;

	/** product. */
	private Product product;

	/** title. */
	private String title;

	/** detail. */
	private String detail;

	/** dayNo. */
	private Integer dayno;

	/**
	 * Constructor.
	 */
	public Itinerary() {
	}

	/**
	 * Set the itineraryId.
	 * 
	 * @param itineraryid
	 *            itineraryId
	 */
	public void setItineraryid(Integer itineraryid) {
		this.itineraryid = itineraryid;
	}

	/**
	 * Get the itineraryId.
	 * 
	 * @return itineraryId
	 */
	public Integer getItineraryid() {
		return this.itineraryid;
	}

	/**
	 * Set the product.
	 * 
	 * @param product
	 *            product
	 */
	public void setProduct(Product product) {
		this.product = product;
	}

	/**
	 * Get the product.
	 * 
	 * @return product
	 */
	public Product getProduct() {
		return this.product;
	}

	/**
	 * Set the title.
	 * 
	 * @param title
	 *            title
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * Get the title.
	 * 
	 * @return title
	 */
	public String getTitle() {
		return this.title;
	}

	/**
	 * Set the detail.
	 * 
	 * @param detail
	 *            detail
	 */
	public void setDetail(String detail) {
		this.detail = detail;
	}

	/**
	 * Get the detail.
	 * 
	 * @return detail
	 */
	public String getDetail() {
		return this.detail;
	}

	/**
	 * Set the dayNo.
	 * 
	 * @param dayno
	 *            dayNo
	 */
	public void setDayno(Integer dayno) {
		this.dayno = dayno;
	}

	/**
	 * Get the dayNo.
	 * 
	 * @return dayNo
	 */
	public Integer getDayno() {
		return this.dayno;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((itineraryid == null) ? 0 : itineraryid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Itinerary other = (Itinerary) obj;
		if (itineraryid == null) {
			if (other.itineraryid != null) {
				return false;
			}
		} else if (!itineraryid.equals(other.itineraryid)) {
			return false;
		}
		return true;
	}

}
