package com.travelgo.otpb.domain;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of Message.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Message implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** messageId. */
	private Integer messageid;

	/** questionType. */
	private Questiontype questiontype;

	/** name. */
	private String name;

	/** email. */
	private String email;

	/** messageText. */
	private String messagetext;

	/** date. */
	private Date date;

	/**
	 * Constructor.
	 */
	public Message() {
	}

	/**
	 * Set the messageId.
	 * 
	 * @param messageid
	 *            messageId
	 */
	public void setMessageid(Integer messageid) {
		this.messageid = messageid;
	}

	/**
	 * Get the messageId.
	 * 
	 * @return messageId
	 */
	public Integer getMessageid() {
		return this.messageid;
	}

	/**
	 * Set the questionType.
	 * 
	 * @param questiontype
	 *            questionType
	 */
	public void setQuestiontype(Questiontype questiontype) {
		this.questiontype = questiontype;
	}

	/**
	 * Get the questionType.
	 * 
	 * @return questionType
	 */
	public Questiontype getQuestiontype() {
		return this.questiontype;
	}

	/**
	 * Set the name.
	 * 
	 * @param name
	 *            name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the name.
	 * 
	 * @return name
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the email.
	 * 
	 * @param email
	 *            email
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * Get the email.
	 * 
	 * @return email
	 */
	public String getEmail() {
		return this.email;
	}

	/**
	 * Set the messageText.
	 * 
	 * @param messagetext
	 *            messageText
	 */
	public void setMessagetext(String messagetext) {
		this.messagetext = messagetext;
	}

	/**
	 * Get the messageText.
	 * 
	 * @return messageText
	 */
	public String getMessagetext() {
		return this.messagetext;
	}

	/**
	 * Set the date.
	 * 
	 * @param date
	 *            date
	 */
	public void setDate(Date date) {
		this.date = date;
	}

	/**
	 * Get the date.
	 * 
	 * @return date
	 */
	public Date getDate() {
		return this.date;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((messageid == null) ? 0 : messageid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Message other = (Message) obj;
		if (messageid == null) {
			if (other.messageid != null) {
				return false;
			}
		} else if (!messageid.equals(other.messageid)) {
			return false;
		}
		return true;
	}

}
