package com.travelgo.otpb.domain;

import java.io.Serializable;
import java.sql.Blob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of product.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Product implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** productId. */
	private Integer productid;

	/** userAccount. */
	private Useraccount useraccount;

	/** hotel. */
	private Hotel hotel;

	/** locationType. */
	private Object locationtype;

	/** photo. */
	private String photo;

	/** title. */
	private String title;

	/** location. */
	private Blob location;

	/** day. */
	private Integer day;

	/** night. */
	private Integer night;

	/** groupSize. */
	private String groupsize;

	/** amount. */
	private Integer amount;

	/** type. */
	private Object type;

	/** meals. */
	private String meals;

	/** photoone. */
	private String photoone;

	/** photoTwo. */
	private String phototwo;

	/** photoThree. */
	private String photothree;

	/** photoFour. */
	private String photofour;

	/** detail. */
	private String detail;

	/** travelDate. */
	private Date traveldate;

	/** The set of Comment. */
	private Set<Comment> commentSet;

	/** The set of Itinerary. */
	private Set<Itinerary> itinerarySet;

	/** The set of Rating. */
	private Set<Rating> ratingSet;

	/**
	 * Constructor.
	 */
	public Product() {
		this.commentSet = new HashSet<Comment>();
		this.itinerarySet = new HashSet<Itinerary>();
		this.ratingSet = new HashSet<Rating>();
	}

	/**
	 * Set the productId.
	 * 
	 * @param productid
	 *            productId
	 */
	public void setProductid(Integer productid) {
		this.productid = productid;
	}

	/**
	 * Get the productId.
	 * 
	 * @return productId
	 */
	public Integer getProductid() {
		return this.productid;
	}

	/**
	 * Set the userAccount.
	 * 
	 * @param useraccount
	 *            userAccount
	 */
	public void setUseraccount(Useraccount useraccount) {
		this.useraccount = useraccount;
	}

	/**
	 * Get the userAccount.
	 * 
	 * @return userAccount
	 */
	public Useraccount getUseraccount() {
		return this.useraccount;
	}

	/**
	 * Set the hotel.
	 * 
	 * @param hotel
	 *            hotel
	 */
	public void setHotel(Hotel hotel) {
		this.hotel = hotel;
	}

	/**
	 * Get the hotel.
	 * 
	 * @return hotel
	 */
	public Hotel getHotel() {
		return this.hotel;
	}

	/**
	 * Set the locationType.
	 * 
	 * @param locationtype
	 *            locationType
	 */
	public void setLocationtype(Object locationtype) {
		this.locationtype = locationtype;
	}

	/**
	 * Get the locationType.
	 * 
	 * @return locationType
	 */
	public Object getLocationtype() {
		return this.locationtype;
	}

	/**
	 * Set the photo.
	 * 
	 * @param photo
	 *            photo
	 */
	public void setPhoto(String photo) {
		this.photo = photo;
	}

	/**
	 * Get the photo.
	 * 
	 * @return photo
	 */
	public String getPhoto() {
		return this.photo;
	}

	/**
	 * Set the title.
	 * 
	 * @param title
	 *            title
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * Get the title.
	 * 
	 * @return title
	 */
	public String getTitle() {
		return this.title;
	}

	/**
	 * Set the location.
	 * 
	 * @param location
	 *            location
	 */
	public void setLocation(Blob location) {
		this.location = location;
	}

	/**
	 * Get the location.
	 * 
	 * @return location
	 */
	public Blob getLocation() {
		return this.location;
	}

	/**
	 * Set the day.
	 * 
	 * @param day
	 *            day
	 */
	public void setDay(Integer day) {
		this.day = day;
	}

	/**
	 * Get the day.
	 * 
	 * @return day
	 */
	public Integer getDay() {
		return this.day;
	}

	/**
	 * Set the night.
	 * 
	 * @param night
	 *            night
	 */
	public void setNight(Integer night) {
		this.night = night;
	}

	/**
	 * Get the night.
	 * 
	 * @return night
	 */
	public Integer getNight() {
		return this.night;
	}

	/**
	 * Set the groupSize.
	 * 
	 * @param groupsize
	 *            groupSize
	 */
	public void setGroupsize(String groupsize) {
		this.groupsize = groupsize;
	}

	/**
	 * Get the groupSize.
	 * 
	 * @return groupSize
	 */
	public String getGroupsize() {
		return this.groupsize;
	}

	/**
	 * Set the amount.
	 * 
	 * @param amount
	 *            amount
	 */
	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	/**
	 * Get the amount.
	 * 
	 * @return amount
	 */
	public Integer getAmount() {
		return this.amount;
	}

	/**
	 * Set the type.
	 * 
	 * @param type
	 *            type
	 */
	public void setType(Object type) {
		this.type = type;
	}

	/**
	 * Get the type.
	 * 
	 * @return type
	 */
	public Object getType() {
		return this.type;
	}

	/**
	 * Set the meals.
	 * 
	 * @param meals
	 *            meals
	 */
	public void setMeals(String meals) {
		this.meals = meals;
	}

	/**
	 * Get the meals.
	 * 
	 * @return meals
	 */
	public String getMeals() {
		return this.meals;
	}

	/**
	 * Set the photoone.
	 * 
	 * @param photoone
	 *            photoone
	 */
	public void setPhotoone(String photoone) {
		this.photoone = photoone;
	}

	/**
	 * Get the photoone.
	 * 
	 * @return photoone
	 */
	public String getPhotoone() {
		return this.photoone;
	}

	/**
	 * Set the photoTwo.
	 * 
	 * @param phototwo
	 *            photoTwo
	 */
	public void setPhototwo(String phototwo) {
		this.phototwo = phototwo;
	}

	/**
	 * Get the photoTwo.
	 * 
	 * @return photoTwo
	 */
	public String getPhototwo() {
		return this.phototwo;
	}

	/**
	 * Set the photoThree.
	 * 
	 * @param photothree
	 *            photoThree
	 */
	public void setPhotothree(String photothree) {
		this.photothree = photothree;
	}

	/**
	 * Get the photoThree.
	 * 
	 * @return photoThree
	 */
	public String getPhotothree() {
		return this.photothree;
	}

	/**
	 * Set the photoFour.
	 * 
	 * @param photofour
	 *            photoFour
	 */
	public void setPhotofour(String photofour) {
		this.photofour = photofour;
	}

	/**
	 * Get the photoFour.
	 * 
	 * @return photoFour
	 */
	public String getPhotofour() {
		return this.photofour;
	}

	/**
	 * Set the detail.
	 * 
	 * @param detail
	 *            detail
	 */
	public void setDetail(String detail) {
		this.detail = detail;
	}

	/**
	 * Get the detail.
	 * 
	 * @return detail
	 */
	public String getDetail() {
		return this.detail;
	}

	/**
	 * Set the travelDate.
	 * 
	 * @param traveldate
	 *            travelDate
	 */
	public void setTraveldate(Date traveldate) {
		this.traveldate = traveldate;
	}

	/**
	 * Get the travelDate.
	 * 
	 * @return travelDate
	 */
	public Date getTraveldate() {
		return this.traveldate;
	}

	/**
	 * Set the set of the Comment.
	 * 
	 * @param commentSet
	 *            The set of Comment
	 */
	public void setCommentSet(Set<Comment> commentSet) {
		this.commentSet = commentSet;
	}

	/**
	 * Add the Comment.
	 * 
	 * @param comment
	 *            Comment
	 */
	public void addComment(Comment comment) {
		this.commentSet.add(comment);
	}

	/**
	 * Get the set of the Comment.
	 * 
	 * @return The set of Comment
	 */
	public Set<Comment> getCommentSet() {
		return this.commentSet;
	}

	/**
	 * Set the set of the Itinerary.
	 * 
	 * @param itinerarySet
	 *            The set of Itinerary
	 */
	public void setItinerarySet(Set<Itinerary> itinerarySet) {
		this.itinerarySet = itinerarySet;
	}

	/**
	 * Add the Itinerary.
	 * 
	 * @param itinerary
	 *            Itinerary
	 */
	public void addItinerary(Itinerary itinerary) {
		this.itinerarySet.add(itinerary);
	}

	/**
	 * Get the set of the Itinerary.
	 * 
	 * @return The set of Itinerary
	 */
	public Set<Itinerary> getItinerarySet() {
		return this.itinerarySet;
	}

	/**
	 * Set the set of the Rating.
	 * 
	 * @param ratingSet
	 *            The set of Rating
	 */
	public void setRatingSet(Set<Rating> ratingSet) {
		this.ratingSet = ratingSet;
	}

	/**
	 * Add the Rating.
	 * 
	 * @param rating
	 *            Rating
	 */
	public void addRating(Rating rating) {
		this.ratingSet.add(rating);
	}

	/**
	 * Get the set of the Rating.
	 * 
	 * @return The set of Rating
	 */
	public Set<Rating> getRatingSet() {
		return this.ratingSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((productid == null) ? 0 : productid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Product other = (Product) obj;
		if (productid == null) {
			if (other.productid != null) {
				return false;
			}
		} else if (!productid.equals(other.productid)) {
			return false;
		}
		return true;
	}

}
