package com.travelgo.otpb.domain;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of questionType.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Questiontype implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** questionTypeId. */
	private Integer questiontypeid;

	/** question. */
	private String question;

	/** The set of Message. */
	private Set<Message> messageSet;

	/**
	 * Constructor.
	 */
	public Questiontype() {
		this.messageSet = new HashSet<Message>();
	}

	/**
	 * Set the questionTypeId.
	 * 
	 * @param questiontypeid
	 *            questionTypeId
	 */
	public void setQuestiontypeid(Integer questiontypeid) {
		this.questiontypeid = questiontypeid;
	}

	/**
	 * Get the questionTypeId.
	 * 
	 * @return questionTypeId
	 */
	public Integer getQuestiontypeid() {
		return this.questiontypeid;
	}

	/**
	 * Set the question.
	 * 
	 * @param question
	 *            question
	 */
	public void setQuestion(String question) {
		this.question = question;
	}

	/**
	 * Get the question.
	 * 
	 * @return question
	 */
	public String getQuestion() {
		return this.question;
	}

	/**
	 * Set the set of the Message.
	 * 
	 * @param messageSet
	 *            The set of Message
	 */
	public void setMessageSet(Set<Message> messageSet) {
		this.messageSet = messageSet;
	}

	/**
	 * Add the Message.
	 * 
	 * @param message
	 *            Message
	 */
	public void addMessage(Message message) {
		this.messageSet.add(message);
	}

	/**
	 * Get the set of the Message.
	 * 
	 * @return The set of Message
	 */
	public Set<Message> getMessageSet() {
		return this.messageSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((questiontypeid == null) ? 0 : questiontypeid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Questiontype other = (Questiontype) obj;
		if (questiontypeid == null) {
			if (other.questiontypeid != null) {
				return false;
			}
		} else if (!questiontypeid.equals(other.questiontypeid)) {
			return false;
		}
		return true;
	}

}
