package com.travelgo.otpb.domain;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of sale.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Sale implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** saleId. */
	private Integer saleid;

	/** userAccount. */
	private Useraccount customeriduseraccount;

	/** qty. */
	private Integer qty;

	/** unitPrice. */
	private Integer unitprice;

	/** amount. */
	private Integer amount;

	/** paymentType. */
	private String paymenttype;

	/** status. */
	private Object status;

	/** date. */
	private Date date;

	/** modifiedDate. */
	private Date modifieddate;

	/**
	 * Constructor.
	 */
	public Sale() {
	}

	/**
	 * Set the saleId.
	 * 
	 * @param saleid
	 *            saleId
	 */
	public void setSaleid(Integer saleid) {
		this.saleid = saleid;
	}

	/**
	 * Get the saleId.
	 * 
	 * @return saleId
	 */
	public Integer getSaleid() {
		return this.saleid;
	}

	/**
	 * Set the userAccount.
	 * 
	 * @param customeriduseraccount
	 *            userAccount
	 */
	public void setCustomeriduseraccount(Useraccount customeriduseraccount) {
		this.customeriduseraccount = customeriduseraccount;
	}

	/**
	 * Get the userAccount.
	 * 
	 * @return userAccount
	 */
	public Useraccount getCustomeriduseraccount() {
		return this.customeriduseraccount;
	}

	/**
	 * Set the qty.
	 * 
	 * @param qty
	 *            qty
	 */
	public void setQty(Integer qty) {
		this.qty = qty;
	}

	/**
	 * Get the qty.
	 * 
	 * @return qty
	 */
	public Integer getQty() {
		return this.qty;
	}

	/**
	 * Set the unitPrice.
	 * 
	 * @param unitprice
	 *            unitPrice
	 */
	public void setUnitprice(Integer unitprice) {
		this.unitprice = unitprice;
	}

	/**
	 * Get the unitPrice.
	 * 
	 * @return unitPrice
	 */
	public Integer getUnitprice() {
		return this.unitprice;
	}

	/**
	 * Set the amount.
	 * 
	 * @param amount
	 *            amount
	 */
	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	/**
	 * Get the amount.
	 * 
	 * @return amount
	 */
	public Integer getAmount() {
		return this.amount;
	}

	/**
	 * Set the paymentType.
	 * 
	 * @param paymenttype
	 *            paymentType
	 */
	public void setPaymenttype(String paymenttype) {
		this.paymenttype = paymenttype;
	}

	/**
	 * Get the paymentType.
	 * 
	 * @return paymentType
	 */
	public String getPaymenttype() {
		return this.paymenttype;
	}

	/**
	 * Set the status.
	 * 
	 * @param status
	 *            status
	 */
	public void setStatus(Object status) {
		this.status = status;
	}

	/**
	 * Get the status.
	 * 
	 * @return status
	 */
	public Object getStatus() {
		return this.status;
	}

	/**
	 * Set the date.
	 * 
	 * @param date
	 *            date
	 */
	public void setDate(Date date) {
		this.date = date;
	}

	/**
	 * Get the date.
	 * 
	 * @return date
	 */
	public Date getDate() {
		return this.date;
	}

	/**
	 * Set the modifiedDate.
	 * 
	 * @param modifieddate
	 *            modifiedDate
	 */
	public void setModifieddate(Date modifieddate) {
		this.modifieddate = modifieddate;
	}

	/**
	 * Get the modifiedDate.
	 * 
	 * @return modifiedDate
	 */
	public Date getModifieddate() {
		return this.modifieddate;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((saleid == null) ? 0 : saleid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Sale other = (Sale) obj;
		if (saleid == null) {
			if (other.saleid != null) {
				return false;
			}
		} else if (!saleid.equals(other.saleid)) {
			return false;
		}
		return true;
	}

}
