package com.travelgo.otpb.domain;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Model class of userAccount.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Useraccount implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** userAccountId. */
	private Integer useraccountid;

	/** profileName. */
	private String profilename;

	/** phone. */
	private String phone;

	/** userType. */
	private Object usertype;

	/** email. */
	private String email;

	/** password. */
	private String password;

	/** status. */
	private Integer status;

	/** The set of product. */
	private Set<Product> productSet;

	/** The set of sale. */
	private Set<Sale> saleSet;

	/**
	 * Constructor.
	 */
	public Useraccount() {
		this.productSet = new HashSet<Product>();
		this.saleSet = new HashSet<Sale>();
	}

	/**
	 * Set the userAccountId.
	 * 
	 * @param useraccountid
	 *            userAccountId
	 */
	public void setUseraccountid(Integer useraccountid) {
		this.useraccountid = useraccountid;
	}

	/**
	 * Get the userAccountId.
	 * 
	 * @return userAccountId
	 */
	public Integer getUseraccountid() {
		return this.useraccountid;
	}

	/**
	 * Set the profileName.
	 * 
	 * @param profilename
	 *            profileName
	 */
	public void setProfilename(String profilename) {
		this.profilename = profilename;
	}

	/**
	 * Get the profileName.
	 * 
	 * @return profileName
	 */
	public String getProfilename() {
		return this.profilename;
	}

	/**
	 * Set the phone.
	 * 
	 * @param phone
	 *            phone
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * Get the phone.
	 * 
	 * @return phone
	 */
	public String getPhone() {
		return this.phone;
	}

	/**
	 * Set the userType.
	 * 
	 * @param usertype
	 *            userType
	 */
	public void setUsertype(Object usertype) {
		this.usertype = usertype;
	}

	/**
	 * Get the userType.
	 * 
	 * @return userType
	 */
	public Object getUsertype() {
		return this.usertype;
	}

	/**
	 * Set the email.
	 * 
	 * @param email
	 *            email
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * Get the email.
	 * 
	 * @return email
	 */
	public String getEmail() {
		return this.email;
	}

	/**
	 * Set the password.
	 * 
	 * @param password
	 *            password
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * Get the password.
	 * 
	 * @return password
	 */
	public String getPassword() {
		return this.password;
	}

	/**
	 * Set the status.
	 * 
	 * @param status
	 *            status
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * Get the status.
	 * 
	 * @return status
	 */
	public Integer getStatus() {
		return this.status;
	}

	/**
	 * Set the set of the product.
	 * 
	 * @param productSet
	 *            The set of product
	 */
	public void setProductSet(Set<Product> productSet) {
		this.productSet = productSet;
	}

	/**
	 * Add the product.
	 * 
	 * @param product
	 *            product
	 */
	public void addProduct(Product product) {
		this.productSet.add(product);
	}

	/**
	 * Get the set of the product.
	 * 
	 * @return The set of product
	 */
	public Set<Product> getProductSet() {
		return this.productSet;
	}

	/**
	 * Set the set of the sale.
	 * 
	 * @param saleSet
	 *            The set of sale
	 */
	public void setSaleSet(Set<Sale> saleSet) {
		this.saleSet = saleSet;
	}

	/**
	 * Add the sale.
	 * 
	 * @param sale
	 *            sale
	 */
	public void addSale(Sale sale) {
		this.saleSet.add(sale);
	}

	/**
	 * Get the set of the sale.
	 * 
	 * @return The set of sale
	 */
	public Set<Sale> getSaleSet() {
		return this.saleSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((useraccountid == null) ? 0 : useraccountid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Useraccount other = (Useraccount) obj;
		if (useraccountid == null) {
			if (other.useraccountid != null) {
				return false;
			}
		} else if (!useraccountid.equals(other.useraccountid)) {
			return false;
		}
		return true;
	}

}
